### 1.데이터 전처리

In [1]:
import pandas as pd
import numpy as np

#### 1-1. 데이터 불러오기

In [2]:
path = "/content/drive/MyDrive/team_project1/data/"

In [3]:
df = pd.read_csv(path + 'Regression_data.csv')
print(df.shape)
df.head()

(4177, 9)

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

#### 1-2. Height 이상치 및 결측치 처리

In [4]:
# 이상치 -> 0.5 이상
# length나 diameter가 동일한 값을 가진 데이터들의 평균값을 활용
df[df['Height'] > 0.5]

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
1417,M,0.705,0.565,0.515,2.210,1.1075,0.4865,0.5120,10
2051,F,0.455,0.355,1.130,0.594,0.3320,0.1160,0.1335,8

In [5]:
df.loc[1417, 'Height'] = df[df['Diameter'] == 0.455]['Height'].mean().round(4)
df.loc[1417, 'Height']

0.1552

In [6]:
df.loc[2051, 'Height'] = df[df['Diameter'] == 0.355]['Height'].mean().round(4)
df.loc[2051, 'Height']

0.1368

In [7]:
# 결측치 처리 -> 값이 0
# # length나 diameter가 동일한 값을 가진 데이터들의 평균값을 활용
df[df['Height'] == 0]

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
1257,I,0.430,0.34,0.0,0.428,0.2065,0.0860,0.1150,8
3996,I,0.315,0.23,0.0,0.134,0.0575,0.0285,0.3505,6

In [8]:
df.loc[1257, 'Height'] = df[df['Diameter'] == 0.34]['Height'].mean().round(4)
df.loc[3996, 'Height'] = df[df['Diameter'] == 0.23]['Height'].mean().round(4)

In [9]:
df[df['Height'] == 0]

Empty DataFrame
Columns: [Sex, Length, Diameter, Height, Whole weight, Shucked weight, Viscera weight, Shell weight, Rings]
Index: []

#### 1-3. 인코딩
- onehot_encoding vs label_encoding
- label_encoding의 경우 피쳐들 간의 관계성이 생겨서 잘못 인식하여 값에 왜곡이 생길 수 있어 선형회귀와 같은 알고리즘에는 보통 적용x [출처](https://hye-z.tistory.com/m/16)

In [10]:
df_encoding = pd.get_dummies(df)
df_encoding.shape

(4177, 11)

In [12]:
# 파일 저장
df_encoding.to_csv(path + "Regression_data_preprocessing.csv", index=False)